WIP

diff --git a/vault-hook b/vault-hook
--- a/vault-hook
+++ b/vault-hook
@@ -1,42 +1,43 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
-# Pre-commit hook that verifies if all files containing 'vault' in the name are encrypted.
-# If not, commit will fail with an error message
-#
-# File should be .git/hooks/pre-commit and executable
-FILES_PATTERN='.*vault.*\.yaml$'
-REQUIRED='ANSIBLE_VAULT'
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
 
-EXIT_STATUS=0
-wipe="\033[1m\033[0m"
-yellow='\033[1;33m'
-# carriage return hack. Leave it on 2 lines.
-cr='
-'
-for f in $(git diff --cached --name-only | grep -E $FILES_PATTERN) ; do
-  # test for the presence of the required bit.
-  MATCH=`head -n1 $f | grep --no-messages $REQUIRED`
-  if [ ! $MATCH ] ; then
-    # Build the list of unencrypted files if any
-    UNENCRYPTED_FILES="$f$cr$UNENCRYPTED_FILES"
-    EXIT_STATUS=1
-  fi
-done
+# Unset variables produce errors
+set -u
 
-if [ ! $EXIT_STATUS = 0 ] ; then
-  echo '# COMMIT REJECTED'
-  echo '# Looks like unencrypted ansible-vault files are part of the commit:'
-  echo '#'
-  while read -r line; do
-    if [ -n "$line" ]; then
-      echo "#\t${yellow}unencrypted:   $line${wipe}"
-    fi
-  done <<< "$UNENCRYPTED_FILES"
-  echo '#'
-  echo "# Please encrypt them with 'ansible-vault encrypt <file>'"
-  echo "#   (or force the commit with '--no-verify')."
-  exit $EXIT_STATUS
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
-exit $EXIT_STATUS
+
+# Redirect output to stderr.
+exec 1>&2
+
+# Check that all changed *.vault files are encrypted
+git diff --cached --name-only -z "$against" | while IFS= read -r -d $'\0' file; do
+	[[ "$file" != *.vault && "$file" != *.vault.yml && "$file" != *.vault.yaml && "$file" != vault.yaml ]] && continue
+	# cut gets symbols 1-2
+	file_status=$(git status --porcelain -- "$file" 2>&1 | cut -c1-2)
+	file_status_index=${file_status:0:1}
+	file_status_worktree=${file_status:1:1}
+	[[ "$file_status_worktree" != ' ' ]] && {
+		echo "ERROR: *.vault file is modified in worktree but not added to the index: $file"
+		echo "Can not check if it is properly encrypted. Use git add or git stash to fix this."
+		exit 1
+	}
+	# check is neither required nor possible for deleted files
+	[[ "$file_status_index" = 'D' ]] && continue
+	head -1 "$file" | grep --quiet '^\$ANSIBLE_VAULT;' || {
+		echo "ERROR: non-encrypted *.vault file: $file"
+		exit 1
+	}
+done
+# Pipe creates separate subshell, we can not use it's variables
+exit $?
 
 ### END DBK
